language: node_js
node_js: 
  - 10
services:
  - docker
before_script:
  - docker pull node/node:10.16.3
  - docker run -d -p 127.0.0.1:80:4567 node/node:10.16.3 /bin/sh
  - docker ps -a
  - docker run node/node:10.16.3 /bin/sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
addons:
  chrome: stable
jobs:
  include:
    - stage: test
    - stage: deploy
      if: branch = master
      script: bash scripts/deploy.sh