language: node_js
node_js: 
  - 10
before_script:
  - google-chrome-stable  --disable-gpu --remote-debugging-port=9222 http://localhost &
addons:
  chrome: stable
jobs:
  include:
    - stage: test
    - stage: deploy
      if: branch = master
      script: bash scripts/deploy.sh