 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node
     steps:
        - checkout
        - run:
            name: Install JRE
            command: apt-get install default-jre
        - run: 
            name: Install dependencies
            command: npm ci
        - run: 
            name: Run tests
            command: npm test
