 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:10.16.3-browsers
     steps:
        - checkout
        - run: 
            name: Install node dependencies
            command: npm ci
        - run:
          name: Install skuid CLI
          command: |
              curl -Lo skuid $(curl -sL https://api.github.com/repos/skuid/skuid-cli/releases/latest | grep "browser_download_url.*linux" | awk -F '"' '{print $4}')
              chmod +x skuid
              sudo mv skuid /usr/local/bin/skuid
        - run: 
            name: Run tests
            command: npm test
        - deploy:
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                scripts/deploy.sh;
              fi
