 version: 2
 jobs:
   build:
     docker:
         - image: selenium/standalone-chrome:3.1.0
     steps:
        - checkout
        - run: 
            name: Install dependencies
            command: npm ci
        - run: 
            name: Run tests
            command: npm test
