 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node
     steps:
        - checkout
        - run: 
            name: Install dependencies
            command: npm ci
        - run:
            name: Install Selenium
            command: wget http://selenium-release.storage.googleapis.com/3.4
        - run: 
          name: Run tests
          command: npm test